backend:
  name: git-gateway
  branch: master  # Change this if your default branch is different

media_folder: "public/uploads"  # Folder for uploaded media files
public_folder: "/uploads"       # Public URL path for media

site_url: "https://masaze-carbon.sk"  # Replace with your live site URL

collections:
  - name: "reviews" # Used in routes, e.g., /admin/collections/blog
    label: "Hodnotenia" # Used in the UI
    folder: "src/content/reviews"  # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete new documents in this collection
    slug: "{{slug}}"
    format: "md"  # Markdown format for files
    fields: # The fields for each document, usually in frontmatter
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Author", name: "author", widget: "text" }
      - { label: "Rating", name: "rating", widget: "string", min: 1, max: 5, step: 1 }
      - { label: "Comment", name: "comment", widget: "text" }
      - { label: "Date Published", name: "datePublished", widget: "datetime" }
      - { label: "Approved", name: "approved", widget: "boolean", default: false }
